version: 1
services:
  - type: web
    name: traefik
    runtime: docker
    plan: starter
    image: traefik
    autoDeploy: true
    dockerCommand:
      - "--api.insecure=true"
      - "--providers.docker=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    envVars:
      - key: SSL_EMAIL
        value: "REPLACE_ME"

  - type: web
    name: n8n
    runtime: docker
    plan: starter
    image: docker.n8n.io/n8nio/n8n
    autoDeploy: true
    envVars:
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: "true"
      - key: N8N_HOST
        value: "${SUBDOMAIN}.${DOMAIN_NAME}"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
      - key: NODE_ENV
        value: "production"
      - key: WEBHOOK_URL
        value: "https://${SUBDOMAIN}.${DOMAIN_NAME}/"
      - key: GENERIC_TIMEZONE
        value: "${GENERIC_TIMEZONE}"
      - key: TZ
        value: "${GENERIC_TIMEZONE}"
