# http:
#   routers:
#     n8n:
#       rule: "Host(`${SUBDOMAIN}.${DOMAIN_NAME}`)"
#       entryPoints:
#         - websecure
#       tls:
#         certResolver: mytlschallenge
#       service: n8n-svc
#       middlewares:
#         - n8n-headers
#   services:
#     n8n-svc:
#       loadBalancer:
#         servers:
#           - url: "http://n8n:5678"
#   middlewares:
#     n8n-headers:
#       headers:
#         sslRedirect: true
#         stsSeconds: 315360000
#         browserXssFilter: true
#         contentTypeNosniff: true
#         forceSTSHeader: true
#         stsIncludeSubdomains: true
#         stsPreload: true
